POST http://localhost:8080/api/create
Content-Type: application/json

{
  "mobileNumber": "0712345678",
  "name": "Madan Ready",
  "email": "eazybytes@gmail.com",
  "accountsDto": {
    "accountType": "current",
    "branchAddress": "123 main street"
  }
}

###
GET http://localhost:8080/api/fetch?mobileNumber=0712345678

###
PUT http://localhost:8080/api/update
Content-Type: application/json

{
  "accountsDto": {
    "accountNumber": 1256937021,
    "accountType": "Savings",
    "branchAddress": "124 Main Street, New York"
  },
  "email": "eazybytes@gmail.com",
  "mobileNumber": "0712345678",
  "name": "Madan Ndonga man"
}

###
DELETE http://localhost:8080/api/delete?mobileNumber=0712345678

